module Ai
  class UpstreamIssueDraft
    MAX_MARKDOWN_BYTES = 768 * 1024

    def self.call(artifact)
      new(artifact).call
    end

    def initialize(artifact)
      @artifact = artifact
      @candidate = artifact.content_json || {}
    end

    def call
      raise ArgumentError, "Artifact is not an upstream candidate." unless @candidate["report_type"] == "upstream_candidate"

      reproduction = JSON.pretty_generate(@candidate.fetch("reproduction"))
      longest_backtick_run = reproduction.scan(/`+/).map(&:length).max || 0
      fence = "`" * [ 3, longest_backtick_run + 1 ].max
      evidence = @candidate.fetch("evidence")

      markdown = <<~MARKDOWN
        # #{@candidate.fetch("title")}

        ## Triage

        - Category: `#{@candidate.fetch("category")}`
        - Run: ##{evidence.fetch("run_id")}

        ## Environment

        - Provider: `#{evidence["provider"]}`
        - Model: `#{evidence["model_id"]}`
        - App version: `#{evidence["app_version"]}`
        - RubyLLM version: `#{evidence["ruby_llm_version"]}`

        ## Expected behavior

        #{@candidate.fetch("expected_behavior")}

        ## Observed behavior

        #{@candidate.fetch("observed_behavior")}

        ## Minimal reproduction steps

        #{@candidate.fetch("reproduction_steps")}

        ## Regression test

        #{@candidate["regression_test_reference"].presence || "Not recorded."}

        ## Redacted Run reproduction JSON

        Review this data before sharing. It was generated by the Run reproduction exporter and excludes binary payloads.

        #{fence}json
        #{reproduction.lines.map { |line| "#{line.chomp}" }.join("\n")}
        #{fence}
      MARKDOWN

      return markdown if markdown.bytesize <= MAX_MARKDOWN_BYTES

      <<~MARKDOWN
        # #{safe_candidate_text("title")}

        ## Triage

        - Category: `#{safe_candidate_text("category")}`
        - Run: ##{evidence.fetch("run_id")}

        The complete issue draft exceeded the #{MAX_MARKDOWN_BYTES}-byte limit.
        Reproduction JSON and long-form notes were omitted. Review the Run in
        Workbench and create a narrower candidate before sharing it upstream.
      MARKDOWN
    end

    private

    def safe_candidate_text(key)
      Ai::RunReproductionExporter.sanitize_text(@candidate[key])
    end
  end
end
